* Rose-Hulman AI XPrize Neural Network
[[https://travis-ci.org/RHIT-XPrize/rhit-xprize-neural-network.svg?branch=master]]

This repository hosts the neural network component of Rose-Hulman's AI
XPrize robot. For more detailed information of the project as a whole,
see [[https://github.com/RHIT-XPrize/rhit-xprize-pipeline][this repo]].

** Instructions
For a quick-and-dirty startup, first =pip3 install --user -r
requirements.txt=. Then use the =build_neural_network.sh= to generate
data, split the data, and train the neural network. Usage is described
below.
** Usage
*** Generate Text Instructions
=generate_text_instructions.py <num-to-generate> <neural-infile> <neural-flips-outfile> <neural-colors-outfile> <neural-letters-outfile>=

Generates =<num-to-generate>= sample instructions and meanings to the
four .csv files =<neural-infile>=, =<neural-flips-outfile>=,
=<neural-colors-outfile>=, and
=<neural-letters-outfile>=.

- =<neural-infile>= holds the raw text (in all caps to reduce the search space)
- =<neural-flips-outfile>= holds a list of 1's and 0's signifying
  whether that instruction was to flip or not
- =<neural-colors-outfile>= holds a boolean matrix of colors:

| Red | Green | Blue | Orange | Yellow |
|-----+-------+------+--------+--------|

- =<neural-letters-outfile>= holds a similar boolean matrix of letters:

| A | B | C | D | E | F | G | H |
|---+---+---+---+---+---+---+---|

These each signify the desired meaning of the corresponding line of
text. Currently, each output entry will have both a color and a
letter.
